unifies files for single and sampled execution

diff --git a/doAll_Baseline_4gram b/doAll_Baseline_4gram
--- a/doAll_Baseline_4gram
+++ b/doAll_Baseline_4gram
@@ -1,17 +1,51 @@
 #!/bin/bash
 
-export ABS_PATH=`pwd`
+LINE_ARGUMENTS=$#
+
+if [[ $LINE_ARGUMENTS -eq 0 ]]; then
+    export ABS_PATH=`pwd`
+
+    JUDGECLASS="toyDataset"
+    
+else
+    SKIP_DATA_EXTRACTION=$1; shift
+    JUDGECLASS=$1; shift
+    TOPICS_CONSIDERED=("$@");
+
+fi
 
 source "${ABS_PATH}/handle_errors"
 source "${ABS_PATH}/colors"
 
+echo "${ABS_PATH}/handle_errors"
+
 
 PURPOSE=baseline
-JUDGECLASS=("toyDataset");
-
-
 CORPLIST=("${JUDGECLASS}")
-SOFIA="/home/jean/Documents/tar-toolkit-core-copy/sofia-ml-read-only/sofia-ml"
+SOFIA="${ABS_PATH}/sofia-ml-read-only/sofia-ml"
+echo $JUDGECLASS
+contains() {
+    : '
+        Utility function that returns true if a given
+        value is within the given array and false otherwise.
+
+        $1 -> value to check
+        $2... -> array
+    '
+
+    value=$1; shift
+    array=("$@")
+
+    for v in "${array[@]}"; do
+        if [[ $v == $value ]]; then
+            true
+            return
+        fi
+    done
+
+    false
+    return
+}
 
 : '
     Iterate over items in CORPLIST
@@ -22,7 +56,13 @@ for CORP in "${CORPLIST[@]}"; do
 
     echo -e "${BLUE}Preparando dataset...${END}"
 
-    ./dofast4 "$CORP"
+    if [[ $LINE_ARGUMENTS -gt 0 ]]; then
+        if [[ $SKIP_DATA_EXTRACTION == "false" ]]; then
+            ./dofast4 "$CORP"
+        fi
+    else
+        ./dofast4 "$CORP"
+    fi
 
     cp "$CORP".df ../"$CORP".df
 
@@ -38,6 +78,15 @@ for CORP in "${CORPLIST[@]}"; do
         IFS=':' read -ra TEXT <<< "$line"
 
         TOPIC="${TEXT[0]}"
+
+        # Skips topics not considered
+        if [[ $LINE_ARGUMENTS -gt 0 ]]; then
+            if ! contains $TOPIC "${TOPICS_CONSIDERED[@]}"; then
+                echo -e "${YELLOW}Skipping topic '$TOPIC'.${END}"
+                continue
+            fi
+        fi
+
         QUERY="${TEXT[1]}"
 
         : '
